export const defaults={mapping:{company:'Company',role:'Position',status:'Status',date:'Application Date',location:'City & Country',salary:'Salary',action:'Next Action',score:'Match Score',source:'',industry:'',arrangement:'',currency:'',followup:'',interviewDate:'',responseDate:'',offerDate:'',rejectionDate:''},groups:{Applied:'applied',Interviewed:'interview',Offer:'offer',Accepted:'accepted',Rejected:'rejected','Draft - Pending Your Review':'draft','Blocked - Not Submitted':'draft','Not Applied - Materials Ready':'draft'},timezone:'Asia/Manila',threshold:14};
export const list=v=>Array.isArray(v)?v:v==null||v===''?[]:[String(v)];
export function day(v,tz='Asia/Manila'){if(!v)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const d=new Date(v);return Number.isNaN(+d)?'':new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export const shift=(s,n)=>new Date(Date.parse(s+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
export function normalize(rows,cfg){return rows.map(r=>{const v=Object.fromEntries(Object.entries(cfg.mapping).map(([k,p])=>[k,r.properties[p]??'']));const gs=[...new Set(list(v.status).map(s=>cfg.groups[s]||Object.entries(cfg.groups).find(([k])=>k.trim().toLowerCase()===s.trim().toLowerCase())?.[1]||'unknown'))];const group=gs.length===1?gs[0]:'unknown';return {...r,...v,group,date:day(v.date,cfg.timezone),status:list(v.status),location:list(v.location),company:String(v.company||'Untitled'),role:String(v.role||'—')};})}
export function filterRows(rows,f){return rows.filter(r=>(!f.search||JSON.stringify(r.properties).toLowerCase().includes(f.search.toLowerCase()))&&(!f.start||r.date&&r.date>=f.start)&&(!f.end||r.date&&r.date<=f.end)&&['status','company','role','location','source','arrangement','industry','action'].every(k=>!f[k]||(f[k]==='Unknown'&&!list(r[k]).length)||list(r[k]).includes(f[k]))&&(!f.group||r.group===f.group));}
export const submitted=r=>['applied','interview','offer','accepted','rejected','withdrawn'].includes(r.group);
export const active=r=>['applied','interview','offer'].includes(r.group);
export function metrics(rows,cfg,now=new Date()){const today=day(now,cfg.timezone),s=rows.filter(submitted),n=g=>s.filter(r=>r.group===g).length;const responded=s.filter(r=>['interview','offer','accepted','rejected'].includes(r.group)||r.responseDate).length;const monday=shift(today,-((new Date(today+'T12:00Z').getUTCDay()+6)%7));return {total:s.length,records:rows.length,active:s.filter(active).length,interview:n('interview'),offer:n('offer')+n('accepted'),rejected:n('rejected'),withdrawn:n('withdrawn'),awaiting:s.filter(r=>r.group==='applied'&&!r.responseDate).length,responded,week:s.filter(r=>r.date>=monday&&r.date<=today).length,month:s.filter(r=>r.date>=today.slice(0,7)+'-01'&&r.date<=today).length,stale:s.filter(r=>r.group==='applied'&&!r.responseDate&&r.date&&r.date<shift(today,-cfg.threshold)),today};}
export function breakdown(rows,key){const map=new Map();for(const r of rows)for(const v of new Set(list(r[key]).length?list(r[key]):['Unknown']))map.set(v,(map.get(v)||0)+1);return [...map].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
export function buckets(rows,unit='week',key='date'){const map=new Map();for(const r of rows){let d=r[key];if(!d)continue;d=d.slice(0,10);if(unit==='month')d=d.slice(0,7)+'-01';if(unit==='week')d=shift(d,-((new Date(d+'T12:00Z').getUTCDay()+6)%7));map.set(d,(map.get(d)||0)+1)}if(!map.size)return [];let start=[...map.keys()].sort()[0],end=[...map.keys()].sort().at(-1),out=[];while(start<=end&&out.length<4000){out.push({name:start,value:map.get(start)||0});start=unit==='month'?new Date(Date.UTC(+start.slice(0,4),+start.slice(5,7),1)).toISOString().slice(0,10):shift(start,unit==='week'?7:1)}return out;}
export function csv(rows){const cols=['company','role','status','date','location','source','salary','action','url'];const cell=v=>'"'+String(Array.isArray(v)?v.join('; '):v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';return [cols,...rows.map(r=>cols.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n')}
